

Data on [[https://github.com/datacamp/careerhub-data][github]]

* Structure

** Motivation
** The data

Feature selection ideas

** Metrics

Regression model, so R^2. For checking for overfitting, check for both
train and test.

** EDA
** Models
** Conclusion

* BMW

[[https://github.com/datacamp/careerhub-data/blob/master/BMW%20Used%20Car%20Sales/bmw.csv][BMW dataset link]]

#begin_src bash
wget -O datasets/bmw.csv https://raw.githubusercontent.com/datacamp/careerhub-data/master/BMW%20Used%20Car%20Sales/bmw.csv
#end_src


Predict price based on other info.


* TODO Make diagrams showing relations between variables

https://graphviz.readthedocs.io/en/stable/

https://diagrams.mingrammer.com/


* TODO Do Lasso and/or Ridge regression

Training and test R^2 are quite close, so it looks like the linear
model is not overfitting much. I'm not sure either Lasso or Ridge can
help much.

Do these with gridsearchCV

* TODO Can I make prediction intervals?

There are quartile based methods, though these do not work for linear regression.

https://online.stat.psu.edu/stat501/lesson/3/3.3

https://github.com/shahejokarian/regression-prediction-interval/blob/master/linear%20regression%20with%20prediction%20interval.ipynb

https://stats.stackexchange.com/questions/147242/how-to-calculate-the-prediction-interval-for-an-ols-multiple-regression

Using statsmodel?

https://stackoverflow.com/questions/17559408/confidence-and-prediction-intervals-with-statsmodels/47191929#47191929

https://www.statsmodels.org/dev/generated/statsmodels.regression.linear_model.OLSResults.get_prediction.html

https://www.reddit.com/r/MachineLearning/comments/3raivl/code_to_calculate_confidence_interval_for_linear/


* TODO Try some tree based method

* TODO Get name of the category dropped by onehotencoder

* TODO Deploy as REST

https://towardsdatascience.com/deploying-a-machine-learning-model-as-a-rest-api-4a03b865c166

#begin_src bash
  curl -X GET http://127.0.0.1:5000/ -d query='20'
#end_src

Getting flask and fetch to play nice

https://stackoverflow.com/questions/63502630/how-to-use-fetch-to-get-post-data-from-flask



* Deps


#+begin_src bash
pip install flask flask-restful
#+end_src

#+begin_src bash
conda install numpy pandas matplotlib seaborn sklearn
#+end_src

#+begin_src bash
pip install diagrams
sudo apt install graphviz # for diagrams
#+end_src

